#Writable config
#Sun Feb 01 13:04:50 CET 2026
postgres.backup.database=jeeeraaah
postgres.backup.exe=/usr/bin/pg_dump
postgres.backup.file=/home/r-uu/develop/github/main/dbbackup/2026.02.01-13.04-text.pg-dump
postgres.backup.host=localhost
postgres.backup.password=jeeeraaah
postgres.backup.port=5432
postgres.backup.username=jeeeraaah
postgres.connection.timeout=30000
postgres.database=mydb
postgres.host=localhost
postgres.max.pool.size=10
postgres.password=changeme
postgres.port=5432
postgres.restore.database=jeeeraaah
postgres.restore.exe=/usr/bin/pg_restore
postgres.restore.file=/home/r-uu/develop/github/main/dbbackup/2026.02.01-12.58-text.pg-dump
postgres.restore.host=localhost
postgres.restore.password=jeeeraaah
postgres.restore.port=5432
postgres.restore.username=jeeeraaah
postgres.schema=public
postgres.ssl.enabled=false
postgres.username=admin
