package de.ruu.app.jeeeraaah.frontend.ui.fx.dash;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Dash}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.03.20 12:21:07:903
 */
public class Dash extends DefaultFXCView<Dash, DashService, DashController>
{
	/**
	 * Provides public access to the controller.
	 * This is needed to call controller methods after the view has been initialized.
	 *
	 * @return the controller instance
	 */
	public DashController getController()
	{
		return controller();
	}
}
