package de.ruu.app.jeeeraaah.frontend.ui.fx.dash;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.util.AbstractEvent;
import jakarta.enterprise.context.ApplicationScoped;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.03.20 12:21:07:961
 */
public interface DashService extends FXCService
{
	/** Event that is fired to indicate that a {@link DashService} component has become available. */
	public class DashComponentReadyEvent extends AbstractEvent<Dash, DashService>
	{
		public DashComponentReadyEvent(final Dash component, final DashService service)
		{
			super(component, service);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			DashComponentReadyEvent
					.class
					.getModule()
					.addReads(DashComponentReadyEvent.class.getClassLoader().getUnnamedModule());
		}

		@ApplicationScoped
		public static class DashComponentReadyEventDispatcher extends EventDispatcher<DashComponentReadyEvent>
		{
		}
	}
}
