#!/bin/bash

# IntelliJ für JPMS-Änderungen aktualisieren

echo "=== IntelliJ JPMS Update ==="
echo ""
echo "1. Invalidate Caches"
echo "   - Datei → Invalidate Caches"
echo "   - Wähle: 'Clear file system cache and Local History'"
echo "   - Wähle: 'Clear downloaded shared indexes'"
echo "   - Click: 'Invalidate and Restart'"
echo ""
echo "2. Nach Neustart:"
echo "   - Rechtsklick auf root/pom.xml"
echo "   - Maven → Reload Project"
echo ""
echo "3. Run-Konfiguration prüfen:"
echo "   - Run → Edit Configurations"
echo "   - Wähle 'DashAppRunner'"
echo "   - Deaktiviere 'Delegate IDE build/run actions to Maven'"
echo "   - Apply → OK"
echo ""
echo "4. Test:"
echo "   - Rechtsklick auf DashAppRunner"
echo "   - Run"
echo ""
echo "Erwartetes Ergebnis: Anwendung startet ohne Lombok-Fehler"
