package de.ruu.lib.postgres.util.ui;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.12.21 09:57:08:113
 */
public interface PostgresUtilUIService extends FXCService
{
}
