package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector;

import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelectorService.TaskGroupSelectorComponentReadyEvent;
import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskGroupSelectorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at
 * 2025.03.20 16:56:31:330
 */
@Slf4j
class TaskGroupSelectorAppRunner extends FXCAppRunner {
	public static void main(String[] args) {
		log.debug("starting TaskGroupSelectorAppRunner.class.getName()");
		FXCAppStartedEvent.addReadsUnnamedModule();
		TaskGroupSelectorComponentReadyEvent.addReadsUnnamedModule();
		FXCAppRunner.run(TaskGroupSelectorApp.class, args);
		log.debug("finished TaskGroupSelectorAppRunner.class.getName()");
	}
}