package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view;

import java.util.Optional;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCApp;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.scene.Parent;
import javafx.stage.Stage;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application {@link TaskViewApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.09.27 16:54:05:953
 */
@Slf4j @Dependent // Explicit: JavaFX Application lifecycle managed by framework, not CDI
// Note: @Dependent (default) required - JavaFX Application lifecycle managed by JavaFX framework.
// Cannot use @Observes(IF_EXISTS) because it requires @ApplicationScoped, hence EventDispatcher pattern.
public class TaskViewApp extends FXCApp
{
	@Inject
	private EventDispatcher<FXCAppStartedEvent> appStartedEventDispatcher;

	// Register event listener after CDI injection completes
	@PostConstruct
	private void registerEventListeners()
	{
		appStartedEventDispatcher.add(this::onAppStarted);
	}

	/**
	 * Called when the FX application has started.
	 */
	private void onAppStarted(FXCAppStartedEvent e)
	{
		if (optionalPrimaryView().isPresent())
		{
			DefaultFXCView<?, ?, ?> view = optionalPrimaryView().get();
			Parent root = view.localRoot();

			Optional<Stage> optionalStage = FXUtil.getStage(root);
			if (optionalStage.isPresent())
			{
				Stage stage = optionalStage.get();
				stage.setTitle("Task View");
			}
			else
			{
				log.warn("no stage found for the primary view: {}", view.getClass().getName());
			}
		}
		else
		{
			log.warn("no primary view found for application: {}", getClass().getName());
		}
	}
}