package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import static de.ruu.lib.fx.FXUtil.getStage;
import static java.util.Objects.isNull;
import static javafx.scene.layout.Priority.ALWAYS;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Optional;

import de.ruu.app.jeeeraaah.common.api.domain.TaskGroupFlat;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelector;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelectorService.TaskGroupSelectorComponentReadyEvent;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController;
import jakarta.inject.Inject;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import javafx.util.StringConverter;
import lombok.NonNull;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.12.18 18:03:02:243
 */
class GanttController extends FXCController.DefaultFXCController<Gantt, GanttService> implements GanttService
{
	@FXML
	private AnchorPane root;
	@FXML
	private VBox vBxRoot;
	@FXML
	private HBox hBxForSelectorAndFilter;
	@FXML
	private VBox vBxForSelector;
	@FXML
	private HBox hBxForFilter;
	@FXML
	private DatePicker dtPckrStart;
	@FXML
	private DatePicker dtPckrEnd;
	@FXML
	private Button btnApply;
	@FXML
	private Button buttonExit;

	// Inject event dispatchers for manual registration in @PostConstruct.
	// Cannot use @Observes(IF_EXISTS) directly because @Dependent beans don't support conditional observers.
	@Inject
	private EventDispatcher<FXCAppStartedEvent> appStartedEventDispatcher;
	@Inject
	private EventDispatcher<TaskGroupSelectorComponentReadyEvent> taskGroupSelectorReadyEventDispatcher;

	// inject components that are used in the user interface
	@Inject
	private TaskGroupSelector taskGroupSelector;
	@Inject
	private TaskTreeTable taskTreeTable;

	private Optional<TaskGroupFlat> selectedTaskGroupDTOFlat = Optional.empty();

	@Override @FXML
	protected void initialize()
	{
		appStartedEventDispatcher.add(e -> onAppStarted(e));
		taskGroupSelectorReadyEventDispatcher.add(e -> onTaskGroupSelectorReady(e));

		// prepare selector
		vBxForSelector.setAlignment(Pos.BOTTOM_LEFT);
		// force task group selector to initialise itself and compose its local root into the ui
		vBxForSelector.getChildren().add(taskGroupSelector.localRoot());
		FXUtil.createTitledBorderAndReplace("group", (Region) vBxForSelector);

		// prepare filter
		configureDatePickerGermanFormat(dtPckrStart);
		configureDatePickerGermanFormat(dtPckrEnd);
		dtPckrStart.setValue(LocalDate.now());
		dtPckrEnd  .setValue(LocalDate.now());
		btnApply.setOnAction(e -> onApply());
		FXUtil.createTitledBorderAndReplace("filter", (Region) hBxForFilter);

		// force task tree table to initialise itself and compose its local root into the ui
		vBxRoot.getChildren().add(taskTreeTable.localRoot());
		VBox.setVgrow(taskTreeTable.localRoot(), ALWAYS);
		HBox.setHgrow(taskTreeTable.localRoot(), ALWAYS);
		FXUtil.setAnchorsInAnchorPaneTo(taskTreeTable.localRoot(), 0);

		// buttonExit.setOnAction(e -> onExit());
	}

	private void onApply()
	{
		taskTreeTable.service().populate(taskGroupSelector.service().selectedTaskGroupProperty().get().id(),
				dtPckrStart.getValue(), dtPckrEnd.getValue());
	}

	/** called when the FX application has started */
	private void onAppStarted(FXCAppStartedEvent e)
	{
		getStage(vBxForSelector).ifPresent(s -> s.setTitle("jeee RAAAH - gantt view"));
	}

	/**
	 * is called as soon as the task group selector is available, performs various initialisations that depend on task
	 * group selector.
	 *
	 * @param e the event that indicates that the groupSelector component is ready
	 */
	private void onTaskGroupSelectorReady(TaskGroupSelectorComponentReadyEvent e)
	{
		@NonNull
		ReadOnlyObjectProperty<TaskGroupFlat> selectedTaskGroupProperty = taskGroupSelector.service()
				.selectedTaskGroupProperty();

		// make sure the listener method is called whenever the selected group in taskGroupSelector changes
		selectedTaskGroupProperty.addListener((obs, old, act) -> onSelectedTaskGroupChanged(act));
	}

	private void onSelectedTaskGroupChanged(TaskGroupFlat actSelection)
	{
		selectedTaskGroupDTOFlat = Optional.ofNullable(actSelection);

		if (isNull(actSelection))
			return;

		taskTreeTable.service().populate(actSelection.id(), dtPckrStart.getValue(), dtPckrEnd.getValue());
	}

	/**
	 * Configures a DatePicker to use German date format (dd.MM.yyyy).
	 *
	 * @param datePicker the DatePicker to configure
	 */
	private void configureDatePickerGermanFormat(DatePicker datePicker)
	{
		DateTimeFormatter germanDateFormatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");

		datePicker.setConverter(new StringConverter<LocalDate>() {
			@Override
			public String toString(LocalDate date)
			{
				return date != null ? germanDateFormatter.format(date) : "";
			}

			@Override
			public LocalDate fromString(String string)
			{
				if (string != null && !string.trim().isEmpty())
				{
					try
					{
						return LocalDate.parse(string, germanDateFormatter);
					}
					catch (DateTimeParseException e)
					{
						return null;
					}
				}
				return null;
			}
		});
	}
}
