package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelectorService.TaskGroupSelectorComponentReadyEvent;
import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link GanttAppRunner}
 * <p>
 * Generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at
 * 2025.12.19 16:00:59:222
 * <p>
 * JPMS Module Access: This runner must call
 * {@code FXCAppRunner.configureModuleAccessForCDI()}
 * before launching the application to configure JPMS module read access for
 * Weld CDI.
 * Application-specific CDI events requiring module access should be registered
 * after configureModuleAccessForCDI() and before {@code FXCAppRunner.run()}.
 */
@Slf4j
class GanttAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting GanttAppRunner.class.getName()");
		// Configure JPMS module access for Weld CDI
		FXCAppRunner.configureModuleAccessForCDI();
		// Register application-specific events for CDI
		TaskGroupSelectorComponentReadyEvent.addReadsUnnamedModule();
		FXCAppRunner.run(GanttApp.class, args);
		log.debug("finished GanttAppRunner.class.getName()");
	}
}