package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.12.18 18:03:02:241
 */
public interface GanttService extends FXCService
{
}