package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Gantt}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.12.18 18:03:02:223
 */
public class Gantt extends DefaultFXCView<Gantt, GanttService, GanttController> implements GanttService
{
	/**
	 * Provides public access to the controller.
	 * This is needed to call controller methods after the view has been initialized.
	 *
	 * @return the controller instance
	 */
	public GanttController getController() { return controller(); }
}