package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.lib.fx.comp.FXCApp;
import javafx.stage.Stage;

/**
 * Java FX Component Application {@link TaskTreeTableApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.12.22 11:45:01:845
 */
public class TaskTreeTableApp extends FXCApp
{
	@Override
	public void start(Stage primaryStage) throws ExceptionInInitializerError
	{
		primaryStage.setResizable(true);

		super.start(primaryStage);

		// Set window size and maximize
		primaryStage.setMaximized(true);

		// Set global font size for the entire application
		// primaryStage.getScene().getRoot().setStyle("-fx-font-size: 10px;");
	}
}