package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner
 * {@link TaskHierarchyPredecessorsAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at
 * 2025.06.03 12:49:45:396
 */
@Slf4j
class TaskHierarchyPredecessorsAppRunner extends FXCAppRunner {
	public static void main(String[] args) {
		log.debug("starting {}", TaskHierarchyPredecessorsAppRunner.class.getName());
		FXCAppRunner.run(TaskHierarchyPredecessorsApp.class, args);
		log.debug("finished {}", TaskHierarchyPredecessorsAppRunner.class.getName());
	}
}